### PR TITLE
Added CLI interface for ad-hoc validation

### PR DESCRIPTION
**Pull request by venthur**
Hi,
i've added a CLI interface for validating local files. For that i've created an `entry_point` in `setup.py` pointing to a new file `openapi_spec_validator/__main__.py`. After you installed the package with pip you are able to run
```bash
$ openapi_spec_validator path_to.yaml
```
to run a validation. This could also be extended to run tests on URLs, not just local files.

### CODE REVIEW

**Comment by p1c2u** [comment]
@venthur thanks. Can you add some tests please?

**Comment by venthur** [comment]
The main scripts are notoriously hard to test, i test here mainly if `sys.exit` was called or not on error.

**Comment by venthur** [comment]
I've replaced the old `optparse` with the newer `argparse` both are part of the standard library but I sometimes confuse the two.

**Comment by p1c2u** [comment]
@venthur maybe [click](http://click.pocoo.org) could be helpful. It has nice [testing module](http://click.pocoo.org/5/testing/)

**Comment by venthur** [comment]
Ok check this out, I've updated this PR to support v2 and v3 schema:

```bash
$ openapi-spec-validator --help
usage: openapi-spec-validator [-h] [--schema {2.0,3.0.0}] filename

positional arguments:
  filename              Absolute or relative path to file

optional arguments:
  -h, --help            show this help message and exit
  --schema {2.0,3.0.0}  OpenAPI schema (default: 3.0.0)
```

if the schema option is not given it defaults to 3.0.0

**Pull request merged**
