### PR TITLE
Use stdlib importlib.resources on python >= 3.9

### PR DESCRIPTION
**Pull request by arthurzam**

### CODE REVIEW

**Comment by arthurzam** [comment]
Hmm, looks mypy shows errors for each other version of import. Tests do pass in each CI run, so at least this.

Maybe we need to add skip line for mypy? Is it acceptable?

**Comment by p1c2u** [comment]
@arthurzam you can try to do similar way I did [for example here](https://github.com/p1c2u/openapi-spec-validator/blob/cab6dd455291721f8f34899ba520b4735c389b81/openapi_spec_validator/validation/protocols.py#L7)

**Comment by arthurzam** [comment]
@p1c2u I'm not sure if this is a good idea. Of course you are upstream and you make the final decision, but force installing backport packages when not needed might be a little bad?

Would you mind to agree to add skip next line comments? I think they were created exactly for such cases.

**Comment by p1c2u** [comment]
By skip line you mean `type: ignore`? If so that's also okay for me

**Comment by andersk** [comment]
Although mypy doesn’t have a special understanding of `try: … except ImportError`, it does have a special understanding of `if sys.version_info >= (3, 9): … else`, so you can use that instead to appease mypy.

**Comment by p1c2u** [comment]
@andersk thanks for your suggestion, I will try that

**Pull request merged**
