### PR TITLE
Adds support for pre-commit

### PR DESCRIPTION
**Pull request by Grimlock257**
Adds support for [pre-commit](https://pre-commit.com/).

Would need this commit to be tagged too if possible so pre-commit can pick it up!

### CODE REVIEW

**Comment by p1c2u** [comment]
Hi @Grimlock257 . Thank you for the contribution. I'm not familiar with pre-commit. How can i test it and  how to tag this commit?

**Comment by Grimlock257** [comment]
> Hi @Grimlock257 . Thank you for the contribution. I'm not familiar with pre-commit. How can i test it and how to tag this commit?

You'll need to install pre-commit: `pip install pre-commit` and then run `pre-commit install`.

You should then be able to do a `pre-commit run` on git staged changes to an `openapi.yaml` file. pre-commit will automatically run when a `git commit` is performed.

I'm not overly familiar with using git tags on a PR as I've never done it before; only to the `master` branch, for master branch it would be `git tag 0.2.9` (or whatever version you want to give it) and then `git push origin --tags`. If you want I can add a tag to this branch with 0.2.9 as the release number (or a different version if you want) and  I'm pretty sure when merged it adds it to the releases.

**Comment by p1c2u** [comment]
Ah I see just version tag. I thought tere needs to some specific one. No worries I will add tag with new version release. Thanks.

**Comment by Grimlock257** [comment]
Yeah, sorry - my bad for not being clear enough :)

**Comment by Grimlock257** [comment]
Hey, would you be able to do the version tag at some point, please! :)

**Comment by bowenwr** [comment]
We could also really use this if it can make it into a version. Thanks!

**Pull request merged**
